name: Daily Commit Workflow

on:
  schedule:
    - cron: '25 18 * * *'  # Adjust the time as needed (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add daily commit by 23f2001915@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date -u)" > daily_status.txt
          git config user.name "GitHub Action Bot"
          git config user.email "23f2001915@ds.study.iitm.ac.in"
          git add daily_status.txt
          git commit -m "Automated daily commit - $(date -u)" || echo "No changes to commit"
          git push
