name: Daily Commit Workflow

on:
  schedule:
    - cron: "15 4 * * *"  # Runs daily at 04:15 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add timestamp file (email: 23f2001915@ds.study.iitm.ac.in)
        run: |
          echo "Last update: $(date -u)" > daily-status.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add daily-status.txt
          git commit -m "Daily update from GitHub Actions [skip ci]" || echo "No changes to commit"
          git push
