name: Daily Commit Workflow

on:
  schedule:
    - cron: '27 4 * * *'  # Runs daily at 04:27 UTC
  workflow_dispatch:      # Optional: allows manual trigger from UI

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add daily commit by 23f2001915@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date -u)" > daily_status.txt
          git config user.name "GitHub Action Bot"
          git config user.email "23f2001915@ds.study.iitm.ac.in"
          git add daily_status.txt
          git commit -m "Automated daily commit - $(date -u)" || echo "No changes to commit"
          git push
